# Generated by Django 5.0.7 on 2024-08-03 16:59

import autos.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('garage', models.CharField(max_length=50, verbose_name='Nombre del Taller')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, default='090 000 000', max_length=15, verbose_name='Número de Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, default='090 000 000', max_length=15, verbose_name='Número de Celular')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('user_type', models.CharField(choices=[('Standard', 'Standard'), ('Pro', 'Pro')], default='Standard', max_length=10, verbose_name='Tipo de Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Patente')),
                ('brand', models.CharField(choices=[('Fiat', 'Fiat'), ('Renault', 'Renault'), ('Toyota', 'Toyota')], max_length=50, verbose_name='Marca')),
                ('moddel', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(default=autos.models.Vehicle.current_year, verbose_name='Año de Fabricación')),
                ('color', models.TextField(max_length=50, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.mechanic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kilometers', models.IntegerField(default=autos.models.Service.current_year, verbose_name='Kilómetraje')),
                ('service_type', models.CharField(choices=[('Filtro de aire', 'Filtro de aire'), ('Filtro de aceite', 'Filtro de aceite'), ('Cambio aceite', 'Cambio aceite'), ('Cambio pastillas de freno', 'Cambio pastillas de freno'), ('Filtro de combustible', 'Filtro de combustible'), ('Cambio de lubricación de transmisión', 'Cambio de lubricación de transmisión'), ('Cambio de amortiguadores', 'Cambio de amortiguadores'), ('Cambio de cubiertas', 'Cambio de cubiertas'), ('Cambio de batería', 'Cambio de batería'), ('Carga Combustible', 'Carga Combustible'), ('Chapista', 'Chapista'), ('Tren delantero', 'Tren delantero'), ('Electricidad', 'Electricidad'), ('Carga Nafta', 'Carga Nafta'), ('Pinchadura', 'Pinchadura'), ('Me hizo un ruido', 'Me hizo un ruido'), ('Cualquier otra cosa', 'Cualquier otra cosa')], max_length=500, verbose_name='Tipo de Servicio')),
                ('coments', models.TextField(blank=True, help_text='Indique cualquier cosa que desee comentar', verbose_name='Comentarios')),
                ('cost', models.IntegerField(verbose_name='Costo del Servicio')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.vehicle')),
            ],
        ),
    ]
