# Generated by Django 5.0.7 on 2024-08-03 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Codeo Electrónico (Opcional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='kilometers',
            field=models.IntegerField(default=0, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.vehicle', verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.user', verbose_name='Titular'),
        ),
    ]
