# Generated by Django 5.0.7 on 2024-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_service_created_at_alter_mechanic_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
    ]
