# Generated by Django 5.0.7 on 2024-08-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_alter_vehicle_car_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autos.mechanic', verbose_name='Mecánico Asignado'),
        ),
    ]
